### ISSUE TITLE
runner spawns on top of screen without care of offset

### ISSUE THREAD

**Issue by sewnie** [phillbush/ctrlmenu#3]
https://user-images.githubusercontent.com/47404953/212524667-c3082da8-5cf3-47a0-a7a0-a0c74a8fe39b.mp4

*Expression of one's frustration*
the terminal that is doing the recording is at the edge of my primary monitor, so is my cursor trying to go past that edge.

**Comment by phillbush** [comment]
That's a shod problem.

Since I have not tested shod on a multimonitor setup, a few elements did not followed the position of the monitor within the larger X11 screen. That happened with the dock (already fixed) and now with the prompt menu.

I fixed it, but referred to  issue [shod/#3](https://github.com/phillbush/shod/issues/3) of `shod` rather than `ctrlmenu`'s #3 issue.  I did not payed attention to the project the issue is linked to.
